---
- name: download nsq
  get_url:
    url={{ nsq_download_url }}
    dest={{ nsq_download_dir }}/nsq.zip

- name: unarchive nsq
  unarchive:
    copy=no
    src={{ nsq_download_dir }}/nsq.zip
    dest={{ nsq_download_dir }}

- name: Install supervisor
  package:
    name=supervisor
    state=present

- name: Start supervisor
  service:
    name=supervisord
    enabled=yes
    state=started

- name: copy binaries from archive into nsq dir
  copy:
    src={{ nsq_download_dir }}/{{ nsq_release }}/{{ item }}
    dest={{ nsq_dir }}
    remote_src=yes
  with_items: nsq_binaries

- include: nsqadmin.yml
  when: nsq_nsqadmin_server

- include: nsqd.yml
  when: nsq_nsqd_server

- include: nsqlookupd.yml
  when: nsq_nsqlookupd_server
