---
- name: create path for on-disk queue files
  file:
    path={{ nsq_nsqd_data_path }}
    state=directory
    mode=0770
    owner={{ nsq_nsqd_user }}
    group={{ nsq_nsqd_group }}

- name: Add supervisor config for nsqd
  template:
    src=etc/supervisor/conf.d/nsq-to-file.conf.j2
    dest=/etc/supervisord.d/nsq-to-file.ini
  notify:
    - restart nsq-to-file