---
- name: add nsqadmin user
  user: name={{ nsq_nsqadmin_user }}
        system=yes
        shell=/bin/false

- name: nsqadmin upstart service
  template: src=etc/supervisor/conf.d/nsqadmin.conf.j2 dest=/etc/supervisor/conf.d/nsqadmin.conf
  notify:
    - restart nsqadmin
