---
- name: add nsqd user
  user:
    name={{ nsq_nsqd_user }}
    system=yes
    shell=/bin/false

- name: create path for on-disk queue files
  file:
    path={{ nsq_nsqd_data_path }}
    state=directory
    mode=0770
    group={{ nsq_nsqd_user }}
    owner={{ nsq_nsqd_group }}

- name: Add supervisor config for nsqd
  template:
    src=etc/supervisor/conf.d/nsqd.conf.j2
    dest=/etc/supervisord.d/nsqd.ini
  notify:
    - restart nsqd

- name: Add config for nsqd
  template:
    src=etc/nsqd.conf.j2
    dest=/etc/nsqd.conf
  notify:
    - restart nsqd
