---
- name: add nsqlookupd user
  user:
    name={{ nsq_nsqlookupd_user }}
    system=yes
    shell=/bin/false

- name: Add supervisor config for nsqlookupd
  template:
    src=etc/supervisor/conf.d/nsqlookupd.conf.j2
    dest=/etc/supervisord.d/nsqlookupd.ini
  notify:
    - restart nsqlookupd

- name: Add config for nsqlookupd
  template:
    src=etc/nsqlookupd.conf.j2
    dest=/etc/nsqlookupd.conf
  notify:
    - restart nsqlookupd
