---
- hosts: all
  roles:
    - wcl-common

- hosts: nsqadmin
  roles:
    - role: nsq
      nsq_nsqadmin_server: true
      nsq_nsqd_server: true
      nsq_nsqlookupd_server: true
      use_ip: false

- hosts: all
  tasks:
    - meta: flush_handlers
    - include: roles/nsq/tasks/test.yml
