---
- hosts: all
  roles:
    - wcl-common

- hosts: nsqadmin
  roles:
    - role: nsq
      nsq_nsqadmin_server: true
      nsq_nsqd_server: true
      nsq_nsqlookupd_server: true

- hosts: all
  tasks:
    - meta: flush_handlers
    - include: roles/nsq/tasks/test.yml
