---
- name: restart nsqd
  supervisorctl:
    name=nsqd
    state=restarted

- name: restart nsqadmin
  supervisorctl:
    name=nsqadmin
    state=restarted

- name: restart nsqlookupd
  supervisorctl:
    name=nsqlookupd
    state=restarted

- name: restart supervisor
  service:
    name=supervisord
    state=restarted

- name: restart nsq-to-file
  supervisorctl:
    name=nsq-to-file
    state=restarted